# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_bbs_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bbs',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
