# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='db_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=20)),
                ('card', models.IntegerField(default=100000000)),
                ('age', models.IntegerField(default=1)),
                ('isstduent', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('login_time', models.DateTimeField(auto_now=True)),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('login_ip', models.GenericIPAddressField()),
                ('group', models.ManyToManyField(to='app01.account_group')),
            ],
        ),
        migrations.CreateModel(
            name='sex_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex_x', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='db_account',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.sex_model'),
        ),
    ]
