# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moniter_conf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='moniter_server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=20, unique=True)),
                ('host_ip', models.GenericIPAddressField()),
                ('cpu_num', models.IntegerField()),
                ('mem_num', models.IntegerField()),
                ('host_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='moniter_servergroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='moniter_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=20, unique=True)),
                ('task', models.CharField(max_length=20)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('start_time', models.DateField()),
                ('host', models.ManyToManyField(to='monitor.moniter_server')),
            ],
        ),
        migrations.CreateModel(
            name='monitor_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=50, unique=True)),
                ('createtime', models.DateField(auto_now_add=True)),
                ('login_ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.AddField(
            model_name='moniter_server',
            name='host_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.moniter_servergroup'),
        ),
    ]
