# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='monitor_serverconf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_num', models.IntegerField()),
                ('mem_num', models.IntegerField()),
                ('host_status', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='moniter_server',
            name='cpu_num',
        ),
        migrations.RemoveField(
            model_name='moniter_server',
            name='host_status',
        ),
        migrations.RemoveField(
            model_name='moniter_server',
            name='mem_num',
        ),
        migrations.AddField(
            model_name='monitor_serverconf',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.moniter_server'),
        ),
    ]
