# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20170718_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor_serverconf',
            name='host',
        ),
        migrations.AddField(
            model_name='moniter_server',
            name='cpu_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moniter_server',
            name='host_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='moniter_server',
            name='mem_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='monitor_serverconf',
        ),
    ]
